package com.txtled.gp_a012.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.txtled.gp_a012.bean.Flame;
import com.txtled.gp_a012.bean.Song;

import com.txtled.gp_a012.bean.dao.FlameDao;
import com.txtled.gp_a012.bean.dao.SongDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig flameDaoConfig;
    private final DaoConfig songDaoConfig;

    private final FlameDao flameDao;
    private final SongDao songDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        flameDaoConfig = daoConfigMap.get(FlameDao.class).clone();
        flameDaoConfig.initIdentityScope(type);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);

        flameDao = new FlameDao(flameDaoConfig, this);
        songDao = new SongDao(songDaoConfig, this);

        registerDao(Flame.class, flameDao);
        registerDao(Song.class, songDao);
    }
    
    public void clear() {
        flameDaoConfig.clearIdentityScope();
        songDaoConfig.clearIdentityScope();
    }

    public FlameDao getFlameDao() {
        return flameDao;
    }

    public SongDao getSongDao() {
        return songDao;
    }

}
